                <tr>
                    <td class="label">User Login:</td>
                    <td class="value">
                        <input id="auth_username" name="auth_username" value="<?php echo($this->get('auth_username'));?>" class="input-text" type="text" />
                    </td>
                </tr>
                <tr>
                    <td class="label">User Password:</td>
                    <td class="value">
                        <input id="auth_password" name="auth_password" value="<?php echo($this->get('auth_password'));?>" class="input-text" type="password" />
                    </td>
                </tr>
