    <div id="connect_login_notice" style="">
        <ul class="msgs">
            <li>
                <ul class="notice-msg">
                     <li>
                         <small><i>For security reasons your user name and password were not saved on the previous step.<br/>
                         Please re-enter your user name and password again to proceed with Magento installation.</i></small>
                     </li>
                </ul>
            </li>
        </ul>
    </div>
